### ISSUE TITLE
Incompatible with Search Plugin

### ISSUE THREAD

**Issue by RalfKerkhoff** [BlakesHeaven/Simple-Stats-Plus#11]
Hi,
activating the plugin will lead to a blank page when a search is performed with the standard search plugin.
No error message, simply a blank page.
Disabling simple stats plus makes search working again.

And there themes a problem with the de_DE language file. If Bludit is set to german, the Plugin name and the description is empty in Bludit backend.

Cheers
Ralf

**Comment by RalfKerkhoff** [comment]
Update - found a soution for the search problem:

In Bludit's settings under the advanced tab, the pages are set to "/" wich means articles are displayed in the frontend like:
https://yoursite.com/articlename

Solution:
change the "/" to something like "/articles/" (without the quotes). Articles will now be displayed as:
https://yoursite.com/articles/articlename

This will make the search work without any problems.

Still open is the problem with the language file

**Comment by BlakesHeaven** [comment]
Hey @RalfKerkhoff , thanks for reporting.
I have replicated both.

I have pushed up a fix for the language file but not yet sorted the release for it. In the meantime, please look for
- "individual-page-counter-tip": "Wenn diese Option aktiviert ist, wird für einzelne veröffentlichte Seiten eine fortlaufende Gesamtsumme erfasst, es sei denn, die Kategorie ist **"Versteckt"**.",

Replace the double quote around **"Versteckt"** with single quotes as **'Versteckt'**

I think I know whereabouts the other strange issue is being caused, but need to fix it properly.

~~In the meantime, with your workaround in place and both working and some visits counted, I think you can revert your workaround back to just "/" instead of "/articles/" and it will still work.~~ Scratch this...

I'll leave this open for now.

**Comment by BlakesHeaven** [comment]
The page counting part was running at siteBodyBegin() to allow the Hitcounter displayed on the page to be correct from the start, however, there seems to be some incompatibility.
Changing the running order back to siteBody**End**() fixes it so for the sake of being 1 count behind I'll leave it running at the end.
